console.log("Hello");
alert("You are learning DOM in js");

// this window generated by browser
console.log(window);
//contain window document which contain all html code in js file
console.dir(window.document.body.childNodes[1]);
//console.dir use to print properties and method of window object



// java script is use to make changes during run time so 
//document.body.style.background = "green"; this make the cahnge during the runtime of your code 


// accessing element by id in js
 
let h = document.getElementById("heading");
console.dir(h);
    

//queary seclector can select the first element  when p tag come it can chage its colour to green 
// and other tag left not chage . And the querySelectorAll can change the all p tage backgroud colour to 
// green

document.querySelector("p").style.background="green";

 console.log(document.body.childNodes[0]);


 console.log(document.firstChild); // it give output Doctype because in html doctype is first chiled
console.log(document.childNodes[0]); //IT Also give the same output live above ..
console.log(document.childNodes[1]); // print html code which contain entire html code
console.log(document.childNodes[2]); // it's give undefine no more child after html

console.log(document.body.childNodes[0]); //Text;
console.log(document.body.childNodes[1]);

// this give all child nodes
console.log(document.childNodes); 
console.log(document.body.childNodes);


console.log("practice question");
 let hp= document.getElementById("Append");
 console.dir(hp);
// hp.innerText =  hp.innerText+"from apana college ";




